import { json, Nx } from '@snailicid3/config'
/**
 * Renders snailicid3's own self-contained `nx.json` from the shared Nx preset.
 *
 * snailicid3 does NOT `extends` `@snailicid3/config/nx-preset.json` (that file is generated by building the very
 * package Nx would need to load `nx.json` to build). Instead this script runs through `tsx` against the exported
 * `Nx.config()` and writes a full, inlined `nx.json` (all `namedInputs` + `targetDefaults`, no `extends`) plus
 * snailicid3-only top-level keys. External repos consume the published `dist/nx-preset.json` via `extends`.
 *
 * Usage: tsx scripts/render-nx.ts # write nx.json tsx scripts/render-nx.ts --check # fail if committed nx.json is stale
 */
import { readFileSync, writeFileSync } from 'node:fs'

const NX_JSON_PATH = 'nx.json'

/**
 * TODO: can we prompt to update maybe after postinstal if stale? it needs to reinstall after updated tho, can that be
 * suppressed somehow i guess it doesnt need to be ?
 */
const nxJson = {
    '$schema': './node_modules/nx/schemas/nx-schema.json',
    '//': 'GENERATED — edit packages/config/src/nx/fragments/*, not this file. Run: pnpm nx:render',
    ...Nx.config({ cwd: process.cwd() }),
    'analytics': true,
    // Snailicid3-only top-level keys (external repos supply their own).
    'nxCloudId': '69ef26f2453df8557a7462c5',
}

const rendered = `${json.prettyPrint(nxJson)}\n`

/** TODO: can any of the configs file write functions be used here? also this NEEDS SNAIL-SH!!!!!!!!!!! */
if (process.argv.includes('--check')) {
    const current = readFileSync(NX_JSON_PATH, 'utf8')
    if (current !== rendered) {
        console.error(
            `${NX_JSON_PATH} is stale — run \`pnpm nx:render\` and commit the result.`,
        )
        process.exit(1)
    }
    console.log(`${NX_JSON_PATH} is up to date.`)
} else {
    writeFileSync(NX_JSON_PATH, rendered)
    console.log(`Wrote ${NX_JSON_PATH} from Nx.config().`)
}
